apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
  {{- if .spec.filters }}
  filters:
  - name: {{ (index .spec.filters 0).name | toYaml }}
    {{- if (index .spec.filters 0).openshiftLabels }}
    openshiftLabels: {{- (index .spec.filters 0).openshiftLabels | toYaml | nindent 6 }}
    {{- end}}
    type: openshiftLabels
  {{- end }}
  {{- if .spec.outputs }}
  outputs:
  - kafka:
      url: {{ (index .spec.outputs 0).kafka.url | toYaml }}
    name: {{ (index .spec.outputs 0).name | toYaml }}
    type: kafka
  {{- end }}
  {{- if .spec.pipelines }}
  pipelines:
  - name: all-to-default
    inputRefs:
    - audit
    - infrastructure
    {{- if .spec.outputs }}
    outputRefs:
    - {{ (index .spec.outputs 0).name }}
    {{- end }}
    {{- if .spec.filters }}
    filterRefs:
    - {{ (index .spec.filters 0).name }}
    {{- end }}
  {{- end }}
  serviceAccount:
    name: collector
  {{- if .spec.managementState }}
  managementState: {{ .spec.managementState }}
  {{- end }}
status:
  # Verify that the configuration is correct
  conditions:
  - type: observability.openshift.io/Valid
    status: "True"

#apiVersion: observability.openshift.io/v1
#kind: ClusterLogForwarder
#metadata:
#  name: instance
#  namespace: openshift-logging
# spec:
#   outputs:
#   - type: "kafka"
#     name: kafka-open
#     # below url is an example
#     kafka:
#       url: tcp://10.11.12.13:9092/test
#   filters:
#   - name: test-labels
#     type: openshiftLabels
#     openshiftLabels:
#       label1: test1
#       label2: test2
#       label3: test3
#       label4: test4
#   pipelines:
#   - name: all-to-default
#     inputRefs:
#     - audit
#     - infrastructure
#     filterRefs:
#     - test-labels
#     outputRefs:
#     - kafka-open
#   serviceAccount:
#     name: collector
