apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: {{ .metadata.name | default "99-worker-blacklist-irdma" }}
spec:
  kernelArguments:
    - "module_blacklist=irdma"
