apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autopilot-logs
  namespace: autopilot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 20Gi
