apiVersion: v1
kind: Secret
metadata:
  name: quay-registry-secret
  namespace: nvidia-tools  
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "quay.io": {
          "username": "sdambo",
          "password": "Shay2011!!!!!!",
          "email": "sdambo@redhat.com",
          "auth": ""
        }
      }
    }
