apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: NMState.v1.nmstate.io
  name: {{ .metadata.name }}
  namespace: openshift-nmstate
spec:
  targetNamespaces:
  - openshift-nmstate
  {{- if .spec.upgradeStrategy }}
  upgradeStrategy: Default
  {{- end }}

