apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .metadata.name }}
  namespace: openshift-sriov-network-operator
spec:
  targetNamespaces:
  - openshift-sriov-network-operator
  {{- if .spec.upgradeStrategy }}
  upgradeStrategy: Default
  {{- end }}
