apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .metadata.name }}
  namespace: nvidia-gpu-operator
spec:
  targetNamespaces:
  - nvidia-gpu-operator
  {{- if .spec.upgradeStrategy }}
  upgradeStrategy: Default
  {{- end }}
