apiVersion: sriovfec.intel.com/v2
kind: SriovFecClusterConfig
metadata:
  name: config
  namespace: vran-acceleration-operators
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
  drainSkip: {{ .spec.drainSkip }} # true if SNO, false by default
  priority: 1
  {{- if .spec.nodeSelector }}
  nodeSelector:
    {{ template "matchNodeSelector" (list .spec.nodeSelector "node-role.kubernetes.io" ) }} # use master for SNO
  {{- end }}
  acceleratorSelector:
    pciAddress: {{ .spec.acceleratorSelector.pciAddress }}
  physicalFunction:  
    pfDriver: "vfio-pci"
    vfDriver: "vfio-pci"
    vfAmount: 16
    bbDevConfig:
      {{- .spec.physicalFunction.bbDevConfig | toYaml | nindent 6 }}
#Recommended configuration for Intel ACC100 eASIC here: https://github.com/intel/sriov-fec-operator/blob/main/spec/sriov-fec-operator.md#sample-cr-for-wireless-fec-acc100
#Recommended configuration for Intel ACC200 (SPR-EE) here: https://github.com/intel/sriov-fec-operator/blob/main/spec/sriov-fec-operator.md#sample-cr-for-wireless-fec-acc200
