apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-filesystem
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
  storageClassName: example-storage-class
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /mnt/local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      {{- range .spec.nodeAffinity.required.nodeSelectorTerms }}
      - matchExpressions:
        {{- range .matchExpressions }}
        - key: {{ template "matchNodeSelectorValue" (list .key "node-role.kubernetes.io" ) }}
          operator: In
          values:
          - ""
        {{- end }}
      {{- end }}
        # Use the hostname if a specific node is used
        # - key: kubernetes.io/hostname
        #   operator: In
        #   values:
        #   - node1-example.com
