apiVersion: v1
kind: Namespace
metadata:
  name: openshift-sriov-network-operator
  {{- if and .metadata .metadata.annotations (hasKey .metadata.annotations "workload.openshift.io/allowed") }}
  annotations:
    workload.openshift.io/allowed: {{ index .metadata.annotations "workload.openshift.io/allowed" }}
  {{- else if .metadata.annotations }}
  annotations:
    {{- range $key, $value := .metadata.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- else }}
  annotations:
    workload.openshift.io/allowed: management
  {{- end }}
