apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .metadata.name }}
  namespace: openshift-sriov-network-operator
spec:
  channel: "stable"
  name: sriov-network-operator
  source: {{ .spec.source }}
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
